### ISSUE TITLE
🚧Initial Project Implementation

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/SWCM#1]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

This is the initial implementation of this project.

### Basics
This console application will give the ability to easily save and retrieve windows credentials basic on the application execution arguments.

### Details
This will be a simple console application that will give us the ability to easily create and retrieve credentials from the Windows Credential Manager.  

**Below are a list of features:**
- Will have 2 components
  - An **exe** console application to help manage credentials
  - Will use the nuget package **CommandLineParser**
  - Using an argument, can be used to be ran in **Add Credential Mode**
    - This will simply ask for the information one piece at a time and then add the credential and exit
  - A mode where you can simply add the credentials using arguments instead of showing the application
- Will have a library component that is used to make it easy to get and set the credentials
  - This is what the console application will use for the actual credential creation and retrieval

CI/CD needs to deploy 2 things.  The console application and the library as a nuget package.

**Extra:**
Look into what it takes to create and add an application as a dotnet tool to be used with the **dotnet CLI**.
If this can be done, this would make it easy to auto install using pre and post scripts

TODO: Finish this

It will allow the passing of arguments which will be the target (credential name) that is storing the user name and password. If the credential exists, then the password will be returned. If it does not exist, it will display the console window to ask for a user name and password to store into the windows credential manager. This ability will allow windows users that are executing the integration tests for the very first time, to create the credentials to be stored in the windows credential manager. After the first time, the application will not ask to enter the credentials because they exist and they will automatically be retrieved from the windows credential manager to be used in the requests.

### Acceptance Criteria

**This issue is finished when:**
- [ ] 
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Issue linked to the correct project.
- [ ] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/[TODO: add project name here]/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/[TODO: add project name here]/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/[TODO: add project name here]/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/[TODO: add project name here]/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/[TODO: add project name here]/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/[TODO: add project name here]/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/[TODO: add project name here]/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/[TODO: add project name here]/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/[TODO: add project name here]/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
This issue has been converted into a `🔬research` issue.
