### ISSUE TITLE
🔬Windows Service/Comms

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/SWCM#11]
### I have done the items below . . .

- [X] I have updated the title without removing the 🔬 emoji.

### What To Research

Do research to figure out how to create a windows service and how to communicate with that service.

The idea is that the windows service can run at all times and be available.  Then another application can communicate with that service to get data or do some work.  

In this context, it is about getting data.  The idea is to have the service return a token to the caller application for use.

### Research Results

asdf

### Acceptance Criteria

**This issue is finished when:**
- [ ] `🔬research` label added to this issue.
- [ ] Research complete and issues created (if needed).
- [ ] If any issues were created, they have been added to the _**Related Work**_ section below.

### ToDo Items

- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct project.
- [ ] Issue linked to the correct milestone.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/[TODO: add project name here]/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/[TODO: add project name here]/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/[TODO: add project name here]/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
