### ISSUE TITLE
🚧Update issue and PR templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/SWCM#4]
### I have done the items below . . .

- [x]  I have updated the title without removing the 🚧 emoji.

### Description

Update and improve project item issue template 

### Acceptance Criteria

**This issue is finished when:**
- Issue templates updated
  - [ ]  bug-issue-template.yml updated
  - [ ]  feature-request-issue-template.yml updated
  - [ ]  release-todo-issue-template.yml updated
  - [ ]  project-item-issue-template.yml updated
  - [ ]  research-issue-template.yml updated
- PR templates updated and text `-template` added to the end of the file before the file extension
  - [ ]  feature-pr.md
  - [ ]  preview-feature-pr.md
  - [ ]  preview-release-pr.md
  - [ ]  production-release-pr.md
- [ ] Add/update config.yml
- [ ]  Update all URL's in all of the templates to match for the project

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [x] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [x] Issue linked to the proper project
- [x] Issue linked to proper milestone

**Comment by kselena** [comment]
Discussed with admin and decision was made to recreate this from a template.  No need to work on this issue.
