### ISSUE TITLE
🔬Research symmetric encryption

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/SWCM#9]
### I have done the items below . . .

- [X] I have updated the title without removing the 🔬 emoji.

### What To Research

Research symmetric encryption for the use of storing data locally in a file.

One place to start is [here](https://docs.microsoft.com/en-us/dotnet/standard/security/decrypting-data).

Create some demo apps to play around with and figure everything out.

### Research Results

asdf

### Acceptance Criteria

**This issue is finished when:**
- [ ] https://github.com/KinsonDigital/[TODO: add project name here]/labels/%F0%9F%94%ACresearch label added to this issue.
- [ ] Research complete and issues created (if needed).
- [ ] If any issues were created, they have been added to the _**Related Work**_ section below.

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [ ] Issue linked to the correct milestone.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/[TODO: add project name here]/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/[TODO: add project name here]/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/[TODO: add project name here]/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
